fs/compat_ioctl: it needs to see the DVBv3 compat stuff
Only the ioctl core should see the DVBv3 compat stuff, as its
contents are not available anymore to the drivers.

As fs/compat_ioctl also handles DVBv3 ioctl's, it needs those
definitions:

    fs/compat_ioctl.c:1345: error: invalid application of âsizeofâ to incomplete type âstruct dvb_frontend_parametersâ
    fs/compat_ioctl.c:1345: error: array type has incomplete element type
    fs/compat_ioctl.c:1345: error: invalid application of âsizeofâ to incomplete type âstruct dvb_frontend_parametersâ
    fs/compat_ioctl.c:1345: error: invalid application of âsizeofâ to incomplete type âstruct dvb_frontend_parametersâ
    fs/compat_ioctl.c:1345: error: invalid application of âsizeofâ to incomplete type âstruct dvb_frontend_parametersâ
    fs/compat_ioctl.c:1345: error: array type has incomplete element type
    fs/compat_ioctl.c:1345: error: invalid application of âsizeofâ to incomplete type âstruct dvb_frontend_parametersâ
    fs/compat_ioctl.c:1345: error: invalid application of âsizeofâ to incomplete type âstruct dvb_frontend_parametersâ
    fs/compat_ioctl.c:1345: error: invalid application of âsizeofâ to incomplete type âstruct dvb_frontend_parametersâ
    fs/compat_ioctl.c:1345: error: array type has incomplete element type
    fs/compat_ioctl.c:1345: error: invalid application of âsizeofâ to incomplete type âstruct dvb_frontend_parametersâ
    fs/compat_ioctl.c:1345: error: invalid application of âsizeofâ to incomplete type âstruct dvb_frontend_parametersâ
    fs/compat_ioctl.c:1345: error: initializer element is not constant
    fs/compat_ioctl.c:1345: error: (near initialization for âioctl_pointer[462]â)
    fs/compat_ioctl.c:1346: error: invalid application of âsizeofâ to incomplete type âstruct dvb_frontend_parametersâ
    fs/compat_ioctl.c:1346: error: array type has incomplete element type
    fs/compat_ioctl.c:1346: error: invalid application of âsizeofâ to incomplete type âstruct dvb_frontend_parametersâ
    fs/compat_ioctl.c:1346: error: invalid application of âsizeofâ to incomplete type âstruct dvb_frontend_parametersâ
    fs/compat_ioctl.c:1346: error: invalid application of âsizeofâ to incomplete type âstruct dvb_frontend_parametersâ
    fs/compat_ioctl.c:1346: error: array type has incomplete element type
    fs/compat_ioctl.c:1346: error: invalid application of âsizeofâ to incomplete type âstruct dvb_frontend_parametersâ
    fs/compat_ioctl.c:1346: error: invalid application of âsizeofâ to incomplete type âstruct dvb_frontend_parametersâ
    fs/compat_ioctl.c:1346: error: invalid application of âsizeofâ to incomplete type âstruct dvb_frontend_parametersâ
    fs/compat_ioctl.c:1346: error: array type has incomplete element type
    fs/compat_ioctl.c:1346: error: invalid application of âsizeofâ to incomplete type âstruct dvb_frontend_parametersâ
    fs/compat_ioctl.c:1346: error: invalid application of âsizeofâ to incomplete type âstruct dvb_frontend_parametersâ
    fs/compat_ioctl.c:1346: error: initializer element is not constant
    fs/compat_ioctl.c:1346: error: (near initialization for âioctl_pointer[463]â)
    fs/compat_ioctl.c:1347: error: invalid application of âsizeofâ to incomplete type âstruct dvb_frontend_eventâ
    fs/compat_ioctl.c:1347: error: array type has incomplete element type
    fs/compat_ioctl.c:1347: error: invalid application of âsizeofâ to incomplete type âstruct dvb_frontend_eventâ
    fs/compat_ioctl.c:1347: error: invalid application of âsizeofâ to incomplete type âstruct dvb_frontend_eventâ
    fs/compat_ioctl.c:1347: error: invalid application of âsizeofâ to incomplete type âstruct dvb_frontend_eventâ
    fs/compat_ioctl.c:1347: error: array type has incomplete element type
    fs/compat_ioctl.c:1347: error: invalid application of âsizeofâ to incomplete type âstruct dvb_frontend_eventâ
    fs/compat_ioctl.c:1347: error: invalid application of âsizeofâ to incomplete type âstruct dvb_frontend_eventâ
    fs/compat_ioctl.c:1347: error: invalid application of âsizeofâ to incomplete type âstruct dvb_frontend_eventâ
    fs/compat_ioctl.c:1347: error: array type has incomplete element type
    fs/compat_ioctl.c:1347: error: invalid application of âsizeofâ to incomplete type âstruct dvb_frontend_eventâ
    fs/compat_ioctl.c:1347: error: invalid application of âsizeofâ to incomplete type âstruct dvb_frontend_eventâ
    fs/compat_ioctl.c:1347: error: initializer element is not constant
    fs/compat_ioctl.c:1347: error: (near initialization for âioctl_pointer[464]â)

Reported-by: Michael Krufky <mkrufky@linuxtv.org>
Signed-off-by: Mauro Carvalho Chehab <mchehab@redhat.com>
Signed-off-by: Angelo G. Del Regno <kholk11@gmail.com>